"""empty message

Revision ID: 7e63af529182
Revises: f8702820118e
Create Date: 2023-09-08 17:22:01.815054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e63af529182'
down_revision = 'f8702820118e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_price', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('economic_details', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('cost_of_living_details', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('weather_details', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('population_details', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('transportation_details', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('real_estate_details', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('real_estate_details')
        batch_op.drop_column('transportation_details')
        batch_op.drop_column('population_details')
        batch_op.drop_column('weather_details')
        batch_op.drop_column('cost_of_living_details')
        batch_op.drop_column('economic_details')
        batch_op.drop_column('home_price')

    # ### end Alembic commands ###
