"""empty message

Revision ID: 89964b4788ef
Revises: f9be21707aaf
Create Date: 2023-08-24 15:16:05.256390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89964b4788ef'
down_revision = 'f9be21707aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_living_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('population', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avg_income', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('summer_comfort_index', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('winter_comfort_index', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unemployment_rate', sa.Float(), nullable=True))
        batch_op.drop_column('living_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('living_cost', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.drop_column('unemployment_rate')
        batch_op.drop_column('winter_comfort_index')
        batch_op.drop_column('summer_comfort_index')
        batch_op.drop_column('avg_income')
        batch_op.drop_column('population')
        batch_op.drop_column('avg_living_cost')

    # ### end Alembic commands ###
