"""empty message

Revision ID: a5ac6834f794
Revises: 89964b4788ef
Create Date: 2023-08-24 15:27:37.105203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ac6834f794'
down_revision = '89964b4788ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('weather')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weather', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
